services:
#    fulguration.example:
#        class: FulgurationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

# ********************************************
#    SONATA
# ********************************************
    admin.categorie:
        class: FulgurationBundle\Admin\CategorieAdmin
        arguments: [~, FulgurationBundle\Entity\Categorie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categories }

    admin.astuce:
        class: FulgurationBundle\Admin\AstuceAdmin
        arguments: [~, FulgurationBundle\Entity\Astuce, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Astuces }

    admin.diplome:
        class: FulgurationBundle\Admin\DiplomeAdmin
        arguments: [~, FulgurationBundle\Entity\Diplome, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Diplomes }

    admin.experience:
        class: FulgurationBundle\Admin\ExperienceAdmin
        arguments: [~, FulgurationBundle\Entity\Experience, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Experiences }

    admin.realisation:
        class: FulgurationBundle\Admin\RealisationAdmin
        arguments: [~, FulgurationBundle\Entity\Realisation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Realisations }